### ISSUE TITLE
dataframe 추론 시 오류 발생

### ISSUE THREAD

**Issue by oneonlee** [ni-inha/Automatic-identification-system-for-fall-event-records-in-EMR-clinical-notes#1]
2023-05-02 22:13:14.380657: I tensorflow/stream_executor/cuda/cuda_blas.cc:1614] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
/media/cds/data/apps/nlp_app/main.py:123: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  dataframe = pd.read_sql(SQL, db_conn)
  inputdate            ptid                                             NSGREC
0  20180902  20170709E00119  [12:29]환자 어지럼증 호소하며 화장실 변기에 주저 앉음. V/S 105/58-...
1  20180902  20180819E00133  병실에서 쿵하는 소리 들려 가보니 환자 병실 안 화장실 앞에 주저앉아있고 양손으로 ...
2  20180902  20180826E00165  EKG monitoring apply중이며 수면 중엔 HR 41회까지 떨어짐. 간간...
3  20180902  20180902E00047  환자 보호자와 같이 화장실 가기 위해 움직이다가 보호자에게 기대면서 넘어짐. 쿵 소...
Data Count from DB: inputdate    4
ptid         4
NSGREC       4
dtype: int64
Traceback (most recent call last):
  File "/media/cds/data/apps/nlp_app/main.py", line 265, in <module>
    main()
  File "/media/cds/data/apps/nlp_app/main.py", line 259, in main
    job()
  File "/media/cds/data/apps/nlp_app/main.py", line 247, in job
    inferenced_df = inference_from_df(df, tokenizer, model)
  File "/media/cds/data/apps/nlp_app/main.py", line 94, in inference_from_df
    predict_y = model.predict(data_X, batch_size=64)
  File "/home/cds/.local/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/cds/.local/lib/python3.10/site-packages/keras/engine/training.py", line 2278, in predict
    raise ValueError(
ValueError: Unexpected result of `predict_function` (Empty batch_outputs). Please use `Model.compile(..., run_eagerly=True)`, or `tf.config.run_functions_eagerly(True)` for more information of where went wrong, or file a issue/bug to `tf.keras`.
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).classifier.kernel
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).classifier.bias
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer's state 'm' for (root).classifier.kernel
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer's state 'm' for (root).classifier.bias
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer's state 'v' for (root).classifier.kernel
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer's state 'v' for (root).classifier.bias

**Comment by oneonlee** [comment]
여전히 같은 오류 발생합니다.

디버깅을 해보니 db로 부터 받아온 dataframe애는 모두 4개의 값이 포함되어 있는데 split_record() 함수의 반환값은 empty가 되어서 그런것 같습니다.

현재 제 db에 들어가 있는 NSGREC 값은 아래와 같습니다. split_record가 올바르게 동작하는지 확인부탁드립니다.

```
[12:29]환자 어지럼증 호소하며 화장실 변기에 주저 앉음. V/S 105/58-76-20-36.7 Check, BST 103mg/dl Check됨. 조식 후 NPO 시행 후 지금까지 NPO 유지하여 그런 것 같다고 표현하며 침상으로 돌아 온 후 혈색과 Condition 괜찮아 짐. 금일은 화장실 ambulation 시행하지 않고 침상 안정 할 것을 교육함;

병실에서 쿵하는 소리 들려 가보니 환자 병실 안 화장실 앞에 주저앉아있고 양손으로 땅 짚고 있는 모습 관찰됨. 수액 폴대가 침대 바퀴에 걸려 수액 줄이 당겨져 있었음. 보호자는 환자 잠들어있는 모습 확인하고 잠시 라운지에 TV 시청하러 간 상황이었고, 환자 혼자 화장실 가려다가 수액 줄이 당겨지면서 넘어져 뒷머리 병실 벽에 부딪혔다고 호소함.

EKG monitoring apply중이며 수면 중엔 HR 41회까지 떨어짐. 간간이 앉아있다 누워있다 하며 rale없이 안정중임. 입냄새 심하여 구강 간호 함.

환자 보호자와 같이 화장실 가기 위해 움직이다가 보호자에게 기대면서 넘어짐. 쿵 소리 들려 가보니 환자 넘어져 있는 상태임.
```
